/* win-prob.js — RJ30-5 (R18 core upgrade): the pure, node-testable live
   win-probability model.

   R18 replaced the original hand-tuned prior/score blend with a VALIDATED
   remaining-time bivariate-Poisson race, walk-forward tested on the 96 played
   2026 matches' real goal/red-card timelines (scripts/proto/validate_inplay.py:
   Brier improves monotonically over the frozen pre-match prior, −48.7% by
   minute 85). The pre-match prior (from the matchup row) is numerically
   inverted to per-90' scoring rates, so at kickoff the live model reproduces
   the prior exactly and every in-play update is generated by the same engine
   family the server forecasts use (exp(mu ± sup/2) Poisson).

   New optional inputs (all default-off, display-only):
     redA/redB — red-card counts; a short-handed side scores at ~65% rate and
                 concedes at ~125% (validated defaults).
     sotA/sotB — live shots-on-target; a BOUNDED run-of-play tilt (±25% of λ,
                 saturating ~6 SoT) nudges rates toward the side creating
                 chances. It cannot flip a prediction on its own.

   Design properties locked by tests/feature/rj30-winprob.test.mjs:
   - outputs are a normalized distribution in [0,1] (clamped off the endpoints);
   - at minute ~1 with 0-0 the result is ~the prior;
   - leading later ⇒ higher leader win%, trailing team crushed (monotone minute);
   - bigger lead ⇒ higher leader win% (monotone margin);
   - drawing late inflates the draw segment vs kickoff;
   - knockout (pd===0) collapses to a two-way {a,b} split (d===0), and a late
     tie favors the higher-prior side (the model's advance pick);
   - never exactly 0 or 1 so the sparkline never flatlines;
   - a missing/NaN minute is treated as a stage default, never NaN.
*/

const EPS = 0.001;   // floor/ceiling so probabilities never hit 0 or 1
const MAXG = 10;     // remaining-goal truncation for the Poisson race
const REG = 90;
const MU_DEFAULT = 0.30;   // baseline log-rate: exp(0.30)≈1.35 goals/side/90'
const RED_OWN = 0.65;      // a side down a man scores at ~65% rate…
const RED_OPP = 1.25;      // …and concedes at ~125%
const TILT_MAX = 0.25;     // SoT tilt clamps at ±25% of λ
const PEN_BETA = 0.90;     // advance-edge logistic on the sup gap at a tie

function clamp(v, lo, hi) { return Math.max(lo, Math.min(hi, v)); }

function isKnockoutStage(stage) {
  return !!stage && stage !== 'group' && stage !== 'group_stage';
}

function pois(k, lam) {
  if (lam <= 0) return k === 0 ? 1 : 0;
  let logp = k * Math.log(lam) - lam;
  for (let i = 2; i <= k; i++) logp -= Math.log(i);
  return Math.exp(logp);
}

/** Poisson race over remaining goals added to the current score. */
function race(la, lb, sa, sb) {
  let a = 0, d = 0, b = 0;
  for (let i = 0; i <= MAXG; i++) {
    const pi = pois(i, la);
    for (let j = 0; j <= MAXG; j++) {
      const p = pi * pois(j, lb);
      const fa = sa + i, fb = sb + j;
      if (fa > fb) a += p;
      else if (fa === fb) d += p;
      else b += p;
    }
  }
  const t = a + d + b || 1;
  return { a: a / t, d: d / t, b: b / t };
}

// ---- prior → rates inversion --------------------------------------------------

const _lamCache = new Map();

/** Invert a 3-way prior {pa,pd,pb} to per-90' rates (la,lb) in the
 *  exp(mu ± sup/2) family: mu is bisected so the race's draw mass matches pd,
 *  sup so the win share matches pa/(pa+pb). Exported for tests. */
export function lambdasFromPrior(pa, pd, pb) {
  const key = `${pa.toFixed(4)}|${pd.toFixed(4)}|${pb.toFixed(4)}`;
  const hit = _lamCache.get(key);
  if (hit) return hit;

  const shareA = pa / (pa + pb || 1);
  let lo = -1.5, hi = 1.5, mu = MU_DEFAULT;
  const supFor = (m) => {
    // inner bisection: sup so that win-share matches
    let slo = -4, shi = 4;
    for (let i = 0; i < 30; i++) {
      const s = (slo + shi) / 2;
      const r = race(Math.exp(m + s / 2), Math.exp(m - s / 2), 0, 0);
      if (r.a / (r.a + r.b || 1) < shareA) slo = s; else shi = s;
    }
    return (slo + shi) / 2;
  };
  if (pd > 0.02) {
    // outer bisection: mu so that draw mass matches (higher mu ⇒ fewer draws)
    for (let i = 0; i < 20; i++) {
      mu = (lo + hi) / 2;
      const s = supFor(mu);
      const r = race(Math.exp(mu + s / 2), Math.exp(mu - s / 2), 0, 0);
      if (r.d > pd) lo = mu; else hi = mu;
    }
    mu = (lo + hi) / 2;
  }
  const sup = supFor(mu);
  const out = { la: Math.exp(mu + sup / 2), lb: Math.exp(mu - sup / 2), sup };
  if (_lamCache.size > 200) _lamCache.clear();
  _lamCache.set(key, out);
  return out;
}

/** Bounded run-of-play tilt from live SoT counts vs the share the rates imply.
 *  Multipliers within [1−TILT_MAX, 1+TILT_MAX]; saturates around 6 total SoT.
 *  Exported for tests. */
export function shotTilt(sotA, sotB, la, lb) {
  const shots = (Number(sotA) || 0) + (Number(sotB) || 0);
  if (!shots) return { ta: 1, tb: 1 };
  const expShareA = la / (la + lb || 1);
  const obsShareA = (Number(sotA) || 0) / shots;
  const w = Math.min(1, shots / 6);
  const t = clamp(w * (obsShareA - expShareA), -TILT_MAX, TILT_MAX);
  return { ta: 1 + t, tb: 1 - t };
}

/**
 * Live win probability — validated Poisson race conditioned on the game state.
 * @param {object} p
 * @param {number} p.pa  pre-match P(team_a wins), a fraction in [0,1].
 * @param {number} p.pd  pre-match P(draw), fraction (0 for knockout — no draw).
 * @param {number} p.pb  pre-match P(team_b wins), fraction.
 * @param {number} p.scoreA current goals for team_a.
 * @param {number} p.scoreB current goals for team_b.
 * @param {number} p.minute current match minute (may be NaN/missing).
 * @param {string} p.stage 'group' | 'round_of_16' | ... (knockout ⇒ no draw).
 * @param {number} [p.redA] red cards against team_a.
 * @param {number} [p.redB] red cards against team_b.
 * @param {number} [p.sotA] live shots-on-target, team_a (bounded tilt).
 * @param {number} [p.sotB] live shots-on-target, team_b.
 * @returns {{a:number,d:number,b:number}} normalized, each in (0,1), summing 1.
 *   For knockout (pd===0) d is exactly 0 and {a,b} sum to 1.
 */
export function liveWinProb({ pa, pd, pb, scoreA, scoreB, minute, stage,
                              redA, redB, sotA, sotB } = {}) {
  const ko = isKnockoutStage(stage) || !(Number(pd) > 0);

  // Sanitize the prior into a proper distribution. Knockout advance priors are
  // 2-way; give the race a realistic draw structure by inverting only the win
  // share (mu stays at the international-scoring default).
  let priorA = Math.max(0, Number(pa) || 0);
  let priorD = ko ? 0 : Math.max(0, Number(pd) || 0);
  let priorB = Math.max(0, Number(pb) || 0);
  let psum = priorA + priorD + priorB;
  if (!(psum > 0)) { priorA = ko ? 0.5 : 1 / 3; priorD = ko ? 0 : 1 / 3; priorB = ko ? 0.5 : 1 / 3; psum = 1; }
  priorA /= psum; priorD /= psum; priorB /= psum;

  const { la: la0, lb: lb0, sup } = ko
    ? lambdasFromPrior(priorA, 0, priorB)
    : lambdasFromPrior(priorA, priorD, priorB);

  const sa = Number(scoreA) || 0;
  const sb = Number(scoreB) || 0;
  const mRaw = Number(minute);
  const m = clamp(Number.isFinite(mRaw) ? mRaw : 50, 0, REG);
  const frac = (REG - m) / REG;

  let la = la0 * frac;
  let lb = lb0 * frac;
  const ra = Number(redA) || 0, rb = Number(redB) || 0;
  if (ra > rb) { la *= RED_OWN; lb *= RED_OPP; }
  else if (rb > ra) { lb *= RED_OWN; la *= RED_OPP; }
  const { ta, tb } = shotTilt(sotA, sotB, la0, lb0);
  la *= ta; lb *= tb;

  const reg = race(la, lb, sa, sb);
  let a = reg.a, d = reg.d, b = reg.b;
  if (ko) {
    // No draw outcome: the level-at-90 branch resolves by ET/pens, favoring the
    // stronger side via a logistic on the rate gap (mirrors the server engine).
    const pShootA = 1 / (1 + Math.exp(-PEN_BETA * sup));
    a += d * pShootA;
    b += d * (1 - pShootA);
    d = 0;
  }

  // Clamp off the endpoints so the sparkline never flatlines, then renormalize.
  const ceil = 1 - EPS;
  a = clamp(a, EPS, ceil);
  b = clamp(b, EPS, ceil);
  d = ko ? 0 : clamp(d, EPS, ceil);
  const sum = a + d + b;
  return { a: a / sum, d: ko ? 0 : d / sum, b: b / sum };
}

// --- series for the sparkline -------------------------------------------------

const STAGE_FOR_SERIES = (found) => found?.stage || found?.actual?.stage || 'group';

// A row is a knockout fixture when it flags itself (is_knockout) or its stage is
// anything other than the group phase. Mirrors matchup-detail.js's isKnockout.
function matchIsKnockout(match) {
  if (!match) return false;
  if (match.is_knockout === true) return true;
  const s = match.stage;
  return !!s && s !== 'group' && s !== 'group_stage';
}

/** Extract the (pa,pd,pb) prior fractions from a matchup row. Group rows carry
 *  `probabilities {team_a_wins,draw,team_b_wins}` (percent); knockout rows carry
 *  `advance_pct_a/_b` (percent, no draw — the "to advance" prior). For a knockout
 *  we force pd=0 and PREFER advance_pct (the real to-advance prior) over the raw
 *  regulation win/draw/win probabilities, falling back to probabilities when
 *  advance_pct is absent. Returns null when no prior exists. */
export function priorFromMatch(match) {
  if (!match) return null;
  const knockout = matchIsKnockout(match);

  // Knockout: prefer the to-advance prior (advance_pct_a/_b ÷ 100, no draw).
  if (knockout && (Number.isFinite(match.advance_pct_a) || Number.isFinite(match.advance_pct_b))) {
    const pa = (match.advance_pct_a || 0) / 100;
    const pb = (match.advance_pct_b || 0) / 100;
    if (pa + pb > 0) return { pa, pd: 0, pb, knockout: true };
  }

  const pr = match.probabilities;
  if (pr && (Number.isFinite(pr.team_a_wins) || Number.isFinite(pr.team_b_wins))) {
    const pa = (pr.team_a_wins || 0) / 100;
    const pd = knockout ? 0 : (pr.draw || 0) / 100;
    const pb = (pr.team_b_wins || 0) / 100;
    if (pa + pd + pb > 0) return { pa, pd, pb, knockout };
  }

  // Non-knockout fallthrough to advance_pct (legacy rows), still two-way.
  if (Number.isFinite(match.advance_pct_a) || Number.isFinite(match.advance_pct_b)) {
    const pa = (match.advance_pct_a || 0) / 100;
    const pb = (match.advance_pct_b || 0) / 100;
    if (pa + pb > 0) return { pa, pd: 0, pb, knockout: true };
  }
  return null;
}

/**
 * Deterministic estimate of how likely a KNOCKOUT match reaches extra time / then
 * penalties, from the current score margin + minute. Pure display heuristic — no
 * randomness, NaN-safe, clamped. Group games (or any non-knockout stage) return
 * {etPct:0, pkPct:0}: there is no ET/PK in the group phase.
 *
 * Intuition:
 *   - Level scoreline, late  ⇒ high chance of ET (nobody's broken the tie yet).
 *   - Level scoreline, early ⇒ moderate — plenty of time for a decisive goal.
 *   - Not level              ⇒ ET only if the trailer equalizes by 90'; that
 *                              chance shrinks as the clock runs and the margin grows.
 *   - pkPct ≈ a fraction of etPct (of the games that reach ET, some stay level
 *     through both added periods and go to spot-kicks).
 *
 * @param {object} p
 * @param {number} p.pa unused reserved (prior a) — accepted for call-site symmetry.
 * @param {number} p.pb unused reserved (prior b).
 * @param {number} p.scoreA current goals for team_a.
 * @param {number} p.scoreB current goals for team_b.
 * @param {number} p.minute current match minute (may be NaN/missing).
 * @param {string} p.stage 'group' ⇒ {0,0}; any knockout stage ⇒ real estimate.
 * @returns {{etPct:number, pkPct:number}} integer percents in [0,100].
 */
export function estimateExtraTime({ scoreA, scoreB, minute, stage } = {}) {
  if (!isKnockoutStage(stage)) return { etPct: 0, pkPct: 0 };

  const sa = Number(scoreA) || 0;
  const sb = Number(scoreB) || 0;
  const margin = Math.abs(sa - sb);
  // Regulation minute clamped to [0,90] for the ET calc (ET itself is 90→120,
  // handled implicitly). A missing/NaN clock is treated as mid-second-half.
  const mRaw = Number(minute);
  const m = clamp(Number.isFinite(mRaw) ? mRaw : 50, 0, 120);
  // Fraction of regulation remaining (0 at/after 90').
  const remain = clamp((90 - m) / 90, 0, 1);

  let et;
  if (margin === 0) {
    // Level: as the clock runs and no one leads, ET grows. Early it's uncertain
    // (someone likely scores), late it's near-inevitable. Base 0.30 → ~0.90.
    et = 0.30 + 0.60 * (1 - remain);
  } else {
    // Not level: ET needs the trailer to erase the margin by 90'. Each goal of
    // deficit roughly halves the shrinking base equalize chance; less time ⇒ less
    // chance. A decided margin late collapses toward 0.
    const base = 0.55 * remain;                 // 0 once regulation is over
    et = base / Math.pow(2, margin - 1);        // 1-goal: base; 2-goal: base/2; …
    // A 2+ goal lead in the final 10' is effectively dead: force ~0.
    if (margin >= 2 && m >= 80) et = Math.min(et, 0.02);
  }
  et = clamp(et, 0, 0.97);

  // Of the ties that reach ET, a fraction stay level through both periods and go
  // to penalties. ~0.55 of ET games historically go to PKs; scale off etPct.
  const pk = et * 0.55;

  const etPct = clampInt(Math.round(et * 100), 0, 100);
  const pkPct = clampInt(Math.round(pk * 100), 0, 100);
  return { etPct, pkPct };
}

function clampInt(v, lo, hi) {
  const n = Math.round(Number(v));
  if (!Number.isFinite(n)) return lo;
  return Math.max(lo, Math.min(hi, n));
}

/**
 * Leader-win% trajectory (percent 0..100) from kickoff → current minute, for the
 * sparkline. Recomputes liveWinProb at 0,15,30,...,currentMinute against the
 * CURRENT score (a smooth "since-kickoff trajectory toward the current state" —
 * we don't persist per-minute history here; the component appends real observed
 * points across polls). Returns [] when the record is not live or has no prior.
 * @param {object} match - the matchup row (prior source).
 * @param {object|null} found - actualForCard() result ({mode, actual:{score_a,score_b,minute}}).
 * @returns {number[]} leader-win% samples in [0,100].
 */
export function winProbSeries(match, found, sampleMinutes) {
  if (!found || found.mode !== 'live') return [];
  const prior = priorFromMatch(match);
  if (!prior) return [];
  const actual = found.actual || {};
  const scoreA = Number(actual.score_a) || 0;
  const scoreB = Number(actual.score_b) || 0;
  const curMin = Number.isFinite(Number(actual.minute)) ? Number(actual.minute) : 50;
  const stage = STAGE_FOR_SERIES(found) === 'group' && prior.knockout ? 'round_of_16' : STAGE_FOR_SERIES(found);

  const minutes = Array.isArray(sampleMinutes) && sampleMinutes.length
    ? sampleMinutes
    : buildMinutes(curMin);

  // Which side is currently the "leader" for the trajectory line? Use the live
  // leader (or the higher prior at a tie) so the line trends toward the team the
  // sparkline is about.
  const leadSide = scoreA > scoreB ? 'a'
    : scoreB > scoreA ? 'b'
    : (prior.pa >= prior.pb ? 'a' : 'b');

  return minutes.map((min) => {
    const r = liveWinProb({ pa: prior.pa, pd: prior.pd, pb: prior.pb, scoreA, scoreB, minute: min, stage });
    return clamp((leadSide === 'a' ? r.a : r.b) * 100, 0, 100);
  });
}

function buildMinutes(curMin) {
  const out = [0];
  for (let t = 15; t < curMin; t += 15) out.push(t);
  out.push(Math.max(curMin, 1));
  // Always at least two points so the sparkline draws a line.
  if (out.length < 2) out.push(curMin);
  return out;
}
